#!/bin/bash

# This is a WIP; not fully tested

# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew install fish

# The basics
brew install tmux gpg nvim z ag bat tree stow diff-so-fancy

# oh-my-fish
curl -L https://get.oh-my.fish | fish
fish -c 'omf install z'

# rvm
curl -sSL https://get.rvm.io | bash -s stable

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
fish -c 'omf install nvm'

# dotfiles
if [ ! -d "$HOME/workspace" ]
then
  mkdir $HOME/workspace
fi

cd $HOME/workspace
if [ ! -d "$HOME/workspace/dotfiles" ]
then
  git clone https://github.com/jchilders/dotfiles.git
fi
cd dotfiles

# link to ~/.config
stow --target=$HOME tmux
stow --target=$HOME fish
stow --target=$HOME nvim
