#!/bin/bash

# This is a WIP; not fully tested

# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew install fish
curl -L https://get.oh-my.fish | fish

# The basics
brew install tmux gpg nvim z ag bat fzf stow tree diff-so-fancy

fish -c 'omf install z'
fich -c 'omf install https://github.com/jethrokuan/fzf'

# rvm
curl -sSL https://get.rvm.io | bash -s stable

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
fish -c 'omf install nvm'

gem install solargraph  # solargraph Ruby LSP server
gem install neovim      # neovim plugin for Ruby

# dotfiles
if [ ! -d "$HOME/workspace" ]
then
  mkdir $HOME/workspace
fi

cd $HOME/workspace
if [ ! -d "$HOME/workspace/dotfiles" ]
then
  git clone https://github.com/jchilders/dotfiles.git
fi
cd dotfiles

# link to ~/.config
stow --target=$HOME tmux
stow --target=$HOME fish
stow --target=$HOME nvim
