#!/usr/bin/env ruby
# frozen_string_literal: true

# Return a list of all branches, remote and local, sorted by most recently modified.

git_cmd = "git for-each-ref --sort=-committerdate --format='%(refname:short)'"
locals = `#{git_cmd} refs/heads`.split
remotes = `#{git_cmd} refs/remotes`.gsub(/^origin\//, '').split

puts (locals | remotes) - ['HEAD']
