#! env /bin/zsh

echo -n "kewa_development..."
mysqldump -u root kewa_development | gzip > $(date +%F)-kewa_development.gz
echo "done"
echo -n "orders..."
mysqldump -u root orders | gzip > $(date +%F)-orders.gz
echo "done"
echo -n "accounts..."
mysqldump -u root accounts | gzip > $(date +%F)-accounts.gz
echo "done"
ls -al
