#!/usr/bin/env zsh

local result="$(tmux list-sessions | fzfp | choose -f : 0)"

if [[ -z $result ]]; then
  return 0
fi

curr_session=$(tmux display-message -p '#S')

if [[ $curr_session == $result ]]; then
  return 0
fi

if [[ -v TMUX ]]; then
  tmux switch-client -t $result
else
  tmux attach -t "$result"
fi
