#!/usr/bin/env zsh

curr_session=$(tmux display-message -p '#S')
script_dir="$HOME/workspace/dotfiles/scripts"
result=$(tmux list-sessions | $script_dir/fzfp | choose -f : 0)

if [[ $curr_session -eq $result ]]; then
  exit 0
fi

if [[ -v TMUX ]]; then
  tmux switch-client -t $result
else
  tmux attach -t "$result"
fi
