:project:
  :url:
    :funding: https://github.com/sponsors/jchilders
    :home: https://github.com/jchilders/%project_name%
    :issues: https://github.com/jchilders/%project_name%/issues
    :source: https://github.com/jchilders/%project_name%
    :versions: https://github.com/jchilders/%project_name%/tags
